version: "3.9"

services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql/data

  server:
    build: ./server/
    command: bash -c "
      python manage.py migrate &&
      gunicorn core.wsgi:application --bind 0.0.0.0:8000
      "
    restart: always
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
    depends_on:
      - db

  celery:
    build: ./server/
    command: celery -A core worker --loglevel=WARNING --concurrency=10
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
    depends_on:
      - db
      - redis
    profiles:
      - celery

  celery_beat:
    build: ./server/
    command: celery -A core beat --loglevel=WARNING --scheduler=django_celery_beat.schedulers:DatabaseScheduler
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
    depends_on:
      - db
      - redis
    profiles:
      - celery

  redis:
    image: redis:alpine
  
  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx/prod.conf:/etc/nginx/conf.d/default.conf
      - ./server/static:/var/www/server/static
      - ./server/media:/var/www/server/media
    ports:
      - "80:80"
    depends_on:
      - server

volumes:
  db:
