version: "3.9"

services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  server:
    build: ./server/
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DB_HOST=db
    volumes:
      - ./server:/app
    ports:
      - '8000:8000'
    depends_on:
      - db

  celery:
    build: ./server/
    command: celery -A core worker --loglevel=WARNING --concurrency=10
    environment:
      - DB_HOST=db
      - DJANGO_DEBUG=
    volumes:
      - ./server:/app
    depends_on:
      - db
      - redis
    profiles:
      - celery

  celery_beat:
    build: ./server/
    command: celery -A core beat --loglevel=WARNING --scheduler=django_celery_beat.schedulers:DatabaseScheduler
    environment:
      - DB_HOST=db
      - DJANGO_DEBUG=
    volumes:
      - ./server:/app
    depends_on:
      - db
      - redis
    profiles:
      - celery

  redis:
    image: redis:alpine
  
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./server/static:/var/www/server/static
      - ./server/media:/var/www/server/media
    ports:
      - "80:80"
    depends_on:
      - server
    profiles:
      - nginx

volumes:
  db:
