version: "3.9"

services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  server:
    build: ./server/
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DB_HOST=db
    volumes:
      - ./server:/app
    ports:
      - '8000:8000'
    depends_on:
      - db

volumes:
  db:
