# Generated by Django 3.2.9 on 2022-03-05 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('ddos', '0002_sitecheckresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecheckresult',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='date updated'),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proxies', to='location.country', verbose_name='country'),
        ),
    ]
