# Generated by Django 3.2.9 on 2022-03-05 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('ddos', '0003_auto_20220305_1845'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sitecheckresult',
            unique_together={('site', 'country')},
        ),
    ]
